

services:
  db:
    image: docker.arvancloud.ir/postgres:14.1
    container_name: jobboard_db_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: jobboard-backend
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./core/:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
  
  
  smtp4dev:
    image: docker.arvancloud.ir/rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev
  
  celery-worker:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core/:/app
      - celerylog-volume:/var/lib/celery-log
    depends_on:
      - redis

    restart: on-failure
  
  celery-flower:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: celery -A core flower --port=5555 --loglevel=info
    ports:
      - '5555:5555'
    volumes:
      - ./core/:/app
    depends_on:
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: celery -A core beat --loglevel=info
    volumes:
      - ./core/:/app
    depends_on:
      - redis
    
  redis:
    container_name: redis3
    image: docker.arvancloud.ir/redis:bookworm
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data


volumes:
  postgres-volume:
  smtp4dev-data:
  redis_data:
  celerylog-volume:
