services:
  db:
    image: docker.arvancloud.ir/postgres:14.1
    container_name: db_api
    ports:
      - 5432:5432
    env_file:
      - db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5

    volumes:
      - postgres-volume:/var/lib/postgresql/data


  django:
    build:
      context: .
      dockerfile: docker/prod.Dockerfile
    
    entrypoint: /entrypoint.sh
    # command: sleep infinity
    container_name: jobboard-backend
    env_file:
      - db.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
    volumes:
      - ./core/:/app
      - static_volume:/app/static_root/
      - media_volume:/app/media/
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    expose:
      - "8000"
    
  nginx:
    image: docker.arvancloud.ir/nginx:1.25.3-alpine
    container_name: jobboard-nginx
    restart: always
    ports: 
      - "9000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static_root/
      - media_volume:/app/media/
    depends_on:
      - django
  
  smtp4dev:
    image: docker.arvancloud.ir/rnwood/smtp4dev:v3
    restart: always
    ports:
      # Change the number before : to the port the web interface should be accessible on
      - '5000:80'
      # Change the number before : to the port the SMTP server should be accessible on
      - '25:25'
      # Change the number before : to the port the IMAP server should be accessible on
      - '143:143'
    volumes:
      # This is where smtp4dev stores the database..
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev



volumes:
  postgres-volume:
  static_volume:
  media_volume:
