

services:
  db:
    image: docker.arvancloud.ir/postgres:14.1
    container_name: db_api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d db"]
      interval: 5s
      timeout: 5s
      retries: 5
    
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: docker/dev.Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: jobboard-backend
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./core/:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres-volume:
