site_name: JB DOC
repo_url: https://github.com/erfan-karimii/jobboard
site_url: https://erfan-karimii.github.io/jobboard/
edit_uri: ''
copyright: Maintained by <a href="www.linkedin.com/in/iam-erfankarimi">Erfan Karimi</a>

nav:
  - Home: index.md
  - Apps:
    - Accounting: accounting.md
    - Job: job.md
  - High Pressure: high-pressure.md
  - Background processing: celery.md
  - Cash strategies: cash.md

theme:
  name: mkdocs
  locale: en
  color_mode: auto
  user_color_mode_toggle: true

extra_css:
  - css/extra.css