# Generated by Django 5.0.2 on 2024-08-21 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0006_alter_companyprofile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('province', models.CharField(choices=[('AL', 'Alborz'), ('AR', 'Ardabil'), ('AE', 'Azerbaijan East'), ('AW', 'Azerbaijan Wast'), ('BU', 'Bushehr'), ('CM', 'Chahar Mahaal and Bakhtiari'), ('FA', 'Fars'), ('GI', 'Gilan'), ('GO', 'Golestan'), ('HA', 'Hamadan'), ('HO', 'Hormozgan'), ('IL', 'Ilam'), ('IS', 'Isfahan'), ('KE', 'Kerman'), ('KM', 'Kermanshah'), ('KN', 'Khorasan North'), ('KR', 'Khorasan Razavi'), ('KS', 'Khorasan South'), ('KH', 'Khuzestan'), ('KB', 'Kohgiluyeh and Boyer-Ahmad'), ('KU', 'Kurdistan'), ('LO', 'Lorestan'), ('MA', 'Markazi'), ('MZ', 'Mazandaran'), ('QA', 'Qazvin'), ('QO', 'Qom'), ('SE', 'Semnan'), ('SB', 'Sistan and Baluchestan'), ('TH', 'Tehran'), ('YZ', 'Yazd'), ('ZN', 'Zanjan')], max_length=50)),
                ('salary', models.CharField(help_text='for every hour', max_length=3)),
                ('info', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.companyprofile')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='job.jobcategory')),
            ],
        ),
    ]
