# Generated by Django 5.0.2 on 2024-08-30 15:06

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_jobapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='cv_file',
            field=models.FileField(default=1, upload_to='', validators=[job.models.validate_resume_size]),
            preserve_default=False,
        ),
    ]
