# Generated by Django 5.0.2 on 2024-08-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_companyprofile_name'),
        ('job', '0005_alter_jobapply_cv_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapply',
            unique_together={('job_seeker', 'job')},
        ),
    ]
