# Generated by Django 5.0.2 on 2024-08-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_companyprofile_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
